# general config
model_class: 'cement_topdown'
scenario: 'baseline'

# logging
logging:
  level: 'DEBUG' # options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# data sources
input_data_path: 'data/baseline_cement_topdown/input'

# model customization
customization:
  lifetime_model_name: 'NormalLifetime'

# visualization
visualization:
  inflow:
    do_visualize: False

# data export
output_path: 'data/baseline_cement_topdown/output'
do_export:
  pickle: False
  csv: True
