# general config
model_class: 'plastics'

# data sources
input_data_path: 'data/baseline_plastics/input'

# model customization
customization:
  lifetime_model_name: 'NormalLifetime'
  end_use_sectors: 'MainSectors' # options: MainSectors, ...
  waste_not_for_recycling: ['Landfill', 'Incineration']

# visualization
visualization:
  inflow:
    do_visualize: True
  sankey:
    do_visualize: True

# data export
output_path: 'data/baseline_plastics/output'
do_export:
  pickle: False
  csv: False
