# general config
model_class: 'plastics'
scenario: 'baseline'

# logging
logging:
  level: 'DEBUG' # options: DEBUG, INFO, WARNING, ERROR, CRITICAL

# data sources
input_data_path: 'data/baseline_plastics/input'

# model customization
customization:
  model_driven: 'production' # options: production, final_demand
  lifetime_model_name: 'NormalLifetime'
  end_use_sectors: 'MainSectors' # options: MainSectors, ...
  waste_not_for_recycling: ['Landfill', 'Incineration']

# visualization
visualization:
  inflow:
    do_visualize: True
  production:
    do_visualize: True
  outflow:
    do_visualize: True
  sankey:
    do_visualize: False
  dashboard:
    do_visualize: False

# data export
output_path: 'data/baseline_plastics/output'
do_export:
  pickle: False
  csv: False
selected_export:
  csv_selected_flows:
    - 'sysenv => Polymer market'
    - 'Plastics market => End use stock'
    - 'Waste collection => Waste sorting'
  csv_selected_stocks:
    - 'End use stock'
  csv_slice_stocks:
    - 'time': [2020, 2030, 2040, 2050]
