# general config
model_class: 'steel'

# data sources
input_data_path: 'data/baseline_steel/input'

# model customization
customization:
  lifetime_model_name: 'NormalLifetime'

# visualization
visualization:
  inflow:
    do_visualize: True
  sankey:
    do_visualize: True

# data export
output_path: 'data/baseline_steel/output'
do_export:
  pickle: False
  csv: True
